### ISSUE TITLE
Raise Exception on iterate

### ISSUE THREAD

**Issue by pastorhudson** [billdeitrick/pypco#33]
Consider this code:
```
        try:
            pco = pypco.PCO(token=access_token)
            people_reports = pco.iterate('/people/v2/reports')
            services_reports = pco.iterate('/services/v2/report_templates')
            return render(request, 'pcoreports/list_reports.html',
                          {'people_reports': people_reports, 'services_reports': services_reports})
```
Today PCO has a 500 error on the services endpoint. So a PCORequestException is raised, but only when the template tries to unpack the generators. Is there a sane way to do a single call that would allow us to Raise an exception on `services_reports = pco.iterate('/services/v2/report_templates')`

By sane I mean without killing the speed, and bogging down the library.

Or is there another way I should try catch that I'm missing?

Things I've considered:
I can unpack the services_reports with a for loop or something and force it to Raise the exception:
```
            try:
                for r in services_reports:
                    print(r)
            except pypco.PCORequestException:
                services_reports = {}
```
But this is ugly and will be lots of repeated code. I don't think it's a deal breaker for 1.0 release, but I'd love your thoughts.

**Comment by billdeitrick** [comment]
My gut feeling with this was that this was something that should simply be solved with a list comprehension in your controller, i.e.:

```python
try:
    services_reports = [record for record in pco.iterate('/services/v2/report_templates')]
except pypco.PCORequestException:
    services_reports = {}
```
This way you're handling the call out to PCO in your controller, and not pushing it off to a view. That way you can handle any exceptions that might arise appropriately, which seems to belong more appropriately in the controller than in the view.

Ultimately, I think the better solution is to add a `list()` function to pypco that wraps `iterate()`, but does the list comprehension for you. That way you can make the actual calls happen immediately, and any exceptions will be thrown immediately as well. I suppose the downside is that you're loading the results from the entire call into memory with this, but there's really no other way to know whether or not you're going to raise an exception than by actually making the API calls.

I don't think it would be wise to handle/hide the exception in pypco, because I don't want to make assumptions about how your application should handle an API call exception.

So, the above would become: 
```python
try:
    services_reports = pco.list('/services/v2/report_templates')
except pypco.PCORequestException:
    services_reports = {}
```

Thoughts? It will be really simple to add `list()`, so I'm planning to do that for 1.0.

**Comment by billdeitrick** [comment]
So, I implemented this. But then pylint reminded me that you can just call the `list()` constructor on any iterable and it will do this for you. 🤦🏻‍♂️

So, you'd have:
```python
try:
    services_reports = list(pco.iterate('/services/v2/report_templates'))
except pypco.PCORequestException:
    services_reports = {}
```
So, I'm thinking that solves this problem. What do you think?

**Comment by pastorhudson** [comment]
Ya I agree some of this could be handled in my controller. I might refactor some of that. But For pcochef I really only need to connect to pco when I’m importing a new report to pco mchef or from pcochef to a users planning center account. So that usually on post and all the pieces are already there. 

I’ll try the list() and see if that works. I really don’t want the library to slow down. I just didn’t know how to catch an error on pco’s end so I can handle it gracefully. This looks like it will solve it!

**Comment by billdeitrick** [comment]
I’ll go go ahead and close this up then...let me know if you find any related (or unrelated) rough edges.
