### ISSUE TITLE
There are missing return types. will it be addressed?

### ISSUE THREAD

**Issue by 07pepa** [billdeitrick/pypco#48]

**Comment by pastorhudson** [comment]
Do you have any info on this? Like what is missing that you'd like to see?

**Comment by 07pepa** [comment]
i do 

look here on public methods like get put post etc...
[look here](https://github.com/billdeitrick/pypco/blob/master/pypco/pco.py)

there are no return types so pycharm does not help  you with programing and other tools like [mypy](https://github.com/python/mypy) does not work when you are programing or running tests (so will improve tesing for you and users of this library)
further more on public method (ones not prefixed by _ )

there are no types on input eather.... even documented it the machine can not read it..

i am willing to fix it


and there is small exaple
```python
def some_method(name:str,age:int,hight:float) -> str:
   return f"hello {name}  U are {age} old you are {hight} high"
```


Ps this is pedantintic... but it will definetly improve your project

**Comment by pastorhudson** [comment]
This would be great! I've used type hints on other projects. And anything that makes pycharm better would be fantastic.

Can you work up a PR?

**Comment by 07pepa** [comment]
yes... it may take some time  it is lots of stuff to change. idealy i will try to add mypy as well to verify that project is internaly corect

**Comment by billdeitrick** [comment]
👋 Hi @07pepa! Type hints would be a great edition. Thanks for your willingness to contribute.

Three things I would ask as you move ahead with this:

1. Let's try to do it in smaller chunks if possible, rather than one big PR that touches every function.
2. Let's not do anything that would break backwards compatibility (unit tests should provide that safety net).
3. I don't think you'll need any additional tests for this, but all code should have unit tests coverage before it is merged to master.

Thank you!

**Comment by 07pepa** [comment]
https://github.com/billdeitrick/pypco/pull/54

and mypy did discover some discrepeancies so adding it as well but it is virtualy configless

**Comment by billdeitrick** [comment]
Completed in #54! Thank you!
